### ISSUE TITLE
[BUG] - Conflict between Spark's guava & Google Cloud's guava

### ISSUE THREAD

**Issue by elarib** [ebiznext/comet-data-pipeline#133]
## Description
 As of today, when using comet in a Spark cluster < 2.1, comet crash because a conflict with guava, and all my attempts to exclude certain guava (like here https://stackoverflow.com/questions/44935550/gae-cloud-storage-guava-nosuchmethoderror-on-appspot), try different guava versions and spark versions does not succeed.

The error is only triggered in “assembly” mode.

## Expected behavior
Run without any problem

## Current Behavior

Crashing with this error :

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:82)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:88)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:74)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:75)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:334)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:290)
	at Main$.main(Main.scala:20)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

## Steps to reproduce
1. Update spark version to 2.1.0
2. Assembly
3. Deploy

**Comment by hayssams** [comment]
+1
