### ISSUE TITLE
[BUG] - inferschema with json file

### ISSUE THREAD

**Issue by nadergharsallaoui** [ebiznext/comet-data-pipeline#91]
## Description
when i try to use inferschema to create a yaml file with all the Attributes using json dataframe i get an error
## Expected behavior
generate yam file with attributes

## Current Behavior
error message:
Exception in thread "main" com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.EmitterException: expected NodeEvent, but got <com.fasterxml.jackson.dataformat.yaml.snakeyaml.events.DocumentEndEvent()>
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:408)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.Emitter$ExpectBlockSequenceItem.expect(Emitter.java:595)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.Emitter$ExpectFirstBlockSequenceItem.expect(Emitter.java:576)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
        at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.close(YAMLGenerator.java:375)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3572)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2909)
        at com.ebiznext.comet.schema.handlers.InferSchemaHandler$.generateYaml(InferSchemaHandler.scala:157)

no yaml file generated 
## Steps to reproduce
1. add test.json file into hdfs : {"name":"nader"}
2. run : spark-submit comet-assembly-0.1.3-SNAPSHOT.jar infer-schema  --domain test --schema testsch --input /tmp/test.json --output file.yaml --with-header false
3. See error

## Complexity estimation
T-Shirt Size:  S

**Comment by AmineSagaama** [comment]
@nadergharsallaoui Is this problem already fixed ? I can take the issue otherwise.

**Comment by nadergharsallaoui** [comment]
@AmineSagaama yes, it's already fixed

**Comment by hayssams** [comment]
@nadergharsallaoui if you think it’s not anymore can you close it please ?
